services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend-production
    ports:
      - "5152:5152"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Secret=${JWT_SECRET}
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend-production
    ports:
      - "5173:5173"