services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: backend-dev
    ports:
      - "5152:5152"
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Secret=${JWT_SECRET}
      - ConnectionStrings__DefaultConnection=${DATABASE_URL}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend